
# SuperNinja App Configuration for Legal Prejudice Analysis Project
# Version: 1.0.0
# Last Updated: 2025-08-29

# Repository information
repository:
  name: "Legal Prejudice Analysis"
  description: "A comprehensive framework and toolset for analyzing, documenting, and responding to potential legal prejudice in judicial proceedings"
  visibility: "public"  # or "private" if your repository is private
  topics:
    - legal-tech
    - risk-assessment
    - judicial-prejudice
    - legal-framework
    - docker

# Docker configuration
docker:
  enabled: true
  files_path: "docker"  # Path to Docker files in your repository
  compose_file: "docker/docker-compose.yml"
  dockerfile_api: "docker/Dockerfile.api"
  dockerfile_web: "docker/Dockerfile.web"
  
  # Build settings
  auto_build:
    enabled: true
    triggers:
      - on_push_to_main
      - on_release
      - on_tag_with_prefix: "v"
    platforms:
      - linux/amd64
      - linux/arm64
  
  # Registry settings
  registry:
    provider: "docker_hub"  # or "github", "aws_ecr", "azure_acr", etc.
    namespace: "your-org-name"  # Your Docker Hub username or organization
    repository_prefix: "legal-prejudice"
    auto_tag:
      use_semver: true
      include_latest: true
      include_sha: true
  
  # Deployment settings
  deployment:
    environments:
      - name: "production"
        trigger: "on_release"
        requires_approval: true
      - name: "staging"
        trigger: "on_push_to_main"
        requires_approval: false
    
    # Health checks after deployment
    health_checks:
      enabled: true
      endpoints:
        - url: "/health"
          expected_status: 200
          timeout_seconds: 30

# Documentation settings
documentation:
  source_path: "docs"
  build_tool: "github_pages"  # or "mkdocs", "sphinx", etc.
  
  # GitHub Pages settings
  github_pages:
    enabled: true
    branch: "gh-pages"
    folder: "docs"
    custom_domain: ""  # Optional: your-domain.com
  
  # Auto-update settings
  auto_update:
    enabled: true
    triggers:
      - on_push_to_docs_folder
      - on_merge_to_main
    update_readme: true
    generate_pdf: true
  
  # API documentation
  api_docs:
    enabled: true
    source_path: "docs/api"
    output_format: "swagger"
    auto_generate: true
    include_examples: true

# Legal system integrations
legal_integrations:
  enabled: true
  
  # Case management systems
  case_management:
    systems:
      - name: "clio"
        enabled: true
        api_version: "v4"
        webhook_path: "/api/webhooks/clio"
        sync_frequency: "daily"
        
      - name: "practice_panther"
        enabled: true
        api_version: "v2"
        webhook_path: "/api/webhooks/practice-panther"
        sync_frequency: "daily"
        
      - name: "mycase"
        enabled: true
        api_version: "v1"
        webhook_path: "/api/webhooks/mycase"
        sync_frequency: "daily"
  
  # Document management systems
  document_management:
    systems:
      - name: "netdocuments"
        enabled: false
        api_version: "v1"
      
      - name: "imanage"
        enabled: false
        api_version: "v2"
  
  # Court systems
  court_systems:
    enabled: false
    systems:
      - name: "pacer"
        enabled: false
      - name: "state_courts"
        enabled: false

# Workflow automation
workflows:
  # Release management
  release:
    enabled: true
    auto_create_from_tag: true
    tag_pattern: "v*.*.*"
    include_changelog: true
    assets:
      - name: "Docker Files"
        path: "docker/**/*"
        package_as: "zip"
      - name: "Documentation"
        path: "docs/**/*"
        package_as: "zip"
      - name: "Templates"
        path: "templates/**/*"
        package_as: "zip"
  
  # Issue management
  issues:
    auto_label:
      enabled: true
      rules:
        - contains: "docker"
          label: "docker"
        - contains: "documentation"
          label: "docs"
        - contains: "api"
          label: "api"
    
    auto_assign:
      enabled: true
      default_assignees:
        - "your-username"
      rules:
        - contains: "docker"
          assign_to: "your-username"
    
    templates:
      enabled: true
      path: ".github/ISSUE_TEMPLATE"
  
  # Pull request management
  pull_requests:
    auto_label: true
    require_tests: true
    auto_merge:
      enabled: false
      require_approvals: 1
    templates:
      enabled: true
      path: ".github/PULL_REQUEST_TEMPLATE"

# Security settings
security:
  dependency_scanning:
    enabled: true
    frequency: "weekly"
    alert_on: "high"
  
  code_scanning:
    enabled: true
    tool: "codeql"
    languages:
      - "javascript"
      - "python"
  
  secret_scanning:
    enabled: true
    notify_on_detection: true

# Notification settings
notifications:
  channels:
    email:
      enabled: true
      recipients:
        - "your-email@example.com"
      events:
        - "deployment_success"
        - "deployment_failure"
        - "security_alert"
    
    webhook:
      enabled: false
      url: ""
      events:
        - "deployment_success"
        - "deployment_failure"
    
    github:
      enabled: true
      events:
        - "issues"
        - "pull_requests"
        - "releases"

# Advanced settings
advanced:
  rate_limiting:
    enabled: true
    max_requests_per_hour: 1000
  
  caching:
    enabled: true
    cache_duration_hours: 24
  
  logging:
    level: "info"  # "debug", "info", "warn", "error"
    retention_days: 30
