name: Deploy to VPS (Apache)

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "dist/**"
      - ".github/workflows/deploy.yml"
      - "package.json"
      - "pnpm-lock.yaml"
      - "vite.config.*"
      env:
  VPS_HOST: ${{ secrets.VPS_HOST }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false  # keep false unless you really need submodules

      # Decide which folder to deploy (dist/ or docs/)
      - name: Detect site output
        id: out
        run: |
          if [ -d dist ]; then echo "dir=dist" >> $GITHUB_OUTPUT;
          elif [ -d docs ]; then echo "dir=docs" >> $GITHUB_OUTPUT;
          else echo "No dist/ or docs/ directory found" >&2; exit 3; fi

    - name: Setup SSH using GitHub secrets
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
        
    - name: Add VPS to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USER: ${{ secrets.VPS_USER }}
        run: |
          rsync -avzr --delete \
            -e "ssh -i id_ci -o StrictHostKeyChecking=no" \
            "${{ steps.out.outputs.dir }}/" \
            "$SSH_USER@$SSH_HOST:/var/www/legal-prejudice-analysis.org/current/"

      - name: Reload Apache
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USER: ${{ secrets.VPS_USER }}
        run: |
          ssh -i id_ci -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "sudo systemctl reload apache2 || true"
